### ISSUE TITLE
"simulateHandleOp succeeded, but should always revert" on sepolia

### ISSUE THREAD

**Issue by grohj** [alchemyplatform/rundler#545]
**Describe the bug**
I'm running rundler locally (port 3000). When trying to submit UserOp using "userop.js" library I get following response from rundler:

```
{
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "simulateHandleOp succeeded, but should always revert"
	},
	"id": 43
}
```

**To reproduce**

1. Run rundler locally with following `.env`: 
```
NODE_HTTP=http://localhost:8545
ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
BUILDER_PRIVATE_KEY=0xsecret
CHAIN_ID=11155111
```

2. Run geth on sepolia via docker-compose
```
version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.10.26
    ports:
      - "8545:8545"
      - "8546:8546"
    command:
      - --miner.gaslimit=12000000
      - --http
      - --http.api=personal,eth,net,web3,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws
      - --ws.api=personal,eth,net,web3,debug
      - --ws.addr=0.0.0.0
      - --ignore-legacy-receipts
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --verbosity=2
      - --nodiscover
      - --maxpeers=4
      - --networkid=11155111
      - --sepolia
      - --syncmode=snap
```
3. Try to build an UserOp using `userop.js` library. It makes several calls, here is the payload for the one that gives the aforementioned error.

```
{"method":"eth_estimateUserOperationGas","params":[{"sender":"0x808e5e293BA1eB5Be66E5985790Ca51248e3ef58","nonce":"0x0","initCode":"0x00000055c0b4fa41dde26a74435ff03692292fbd5fbfb9cf0000000000000000000000005250172c5526318599ca08f5fc7177387869b7fd0000000000000000000000000000000000000000000000000000000000000000","callData":"0x18dfb3c7000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000020000000000000000000000003870419ba2bbf0127060bcb37f69a1b1c090992b0000000000000000000000003870419ba2bbf0127060bcb37f69a1b1c090992b0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000808e5e293ba1eb5be66e5985790ca51248e3ef580000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000808e5e293ba1eb5be66e5985790ca51248e3ef58000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","callGasLimit":"0x0","verificationGasLimit":"0x0","preVerificationGas":"0x0","maxFeePerGas":"0x0","maxPriorityFeePerGas":"0x3","paymasterAndData":"0x","signature":"0xcda8dd361f56e67cc4c39ce612ea6e428b48e2f2930ce0730dbf44539396de2b46acca47e40688e93ecdd7018ff73f348b20b0952b1ccee85acd0c6b99eadd4e1b"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"],"id":43,"jsonrpc":"2.0"}
```

**Expected behavior**

Please provide more details why it is not reverting, when it always should (as the response says).

**Logs**

Logs from geth (it actually looks like it reverts there: 

```
WARN [01-05|15:08:00.192] Served eth_call                          conn=172.21.0.1:47966 reqid=4  duration="305.663µs" err="execution reverted"                 errdata=0x8b9171020000000000000000000000000000000000000000000000000000000000001714000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000
```

Logs from rundler are empty.

**Remarks**
I'm also using Infura RPC for sepolia for the userop.js library, but I'm setting custom bundlerRpc as per documentation.

Also the whole reason I needed to setup `geth` was because the `debug_traceCall` is not supported by public RPCs. How could one go about deploying whole AA setup as a standalone custom solution. Is Geth required in every case, or there is a workaround to avoid making these debug calls? I saw that original bundler implementation has `--unsafe` mode where it skips this. Would that be possible in case of rundler?
